# Generated by Django 5.2.18 on 2026-10-09 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('accepted_by_provider', 'Accepted by provider'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unassigned', max_length=24)),
                ('per_minute_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('billed_minutes', models.PositiveIntegerField(default=0)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('talk_seconds', models.PositiveIntegerField(default=0)),
                ('ended_by', models.CharField(blank=True, choices=[('user', 'User'), ('provider', 'Provider'), ('system : Insufficient Balance', 'System : Insufficient Balance')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_provider', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='one_active_session_per_user')],
            },
        ),
    ]
